### ISSUE TITLE
[In-Game documentation] The Grand Book of Golem Mastery

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-GolemConstruction#10]
So I am currently experimenting with golems (again). Just built a lesser clay golem for the first time. \o/

One thing I currently do not know well is what ingredients I need. These can probably be found out in-game and with trial and error, but would it be possible to provide a useful book here?

A book written by some mage who was tragically killed by his golem, but he had some kind of diary.

That diary is like a newbie-golem help, e. g. "for a lesser clay golem, I found I need 20 lb of clay at the least". "For a medium clay golem I need 50 lb of clay" and so forth.

As comparison, in the Dusk NPC mod, the leprechaun gives us a helpful book which lists the required ingredients. Perhaps that is "too meta" and provides out of character information, but a diary that mentions these things would be neat. And perhaps, after reading that diary, it could also register in the journal what is necessary. Right now I evidently seem to lack quite some things e. g. I can not build a iron golem.

**Comment by Argent77** [comment]
> One thing I currently do not know well is what ingredients I need. These can probably be found out in-game and with trial and error, but would it be possible to provide a useful book here?

The required ingredients are listed right there in the golem tomes, together with all the other requirements (like minimum level, etc.). For even more details you can always look up the golem information document in the readme folder of the mod.
