### ISSUE TITLE
[Purchase material for smaller golems] Ingredients at a store

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-GolemConstruction#11]
Would it perhaps be possible to add purchaseable ingredients for the smaller golems?

This can be limited so that we can only build one, e. g. purchase ingrediends for each of
one of the lesser types of golems. These ingrediens can be very expensive too - no problem,
e. g. 5000 gold coins for ingredients required for a lesser golem, or even more.

As you also maintain the warez-mod in regards to unusual items, perhaps he can also
sell ingredients for lesser golems (for one). Would give him a bit of extra money.

There should then be a check such as "if the golem construction mod is installed, add
to the store enough ingredients for one lesser golem of each type". That way the player
can experiment a bit more easily with the golems. Right now I don't have the iron golem
tested.

(This should only work for one lesser golem; the more important golems can be obtained
by finding the things necessary instead. So this is really more of a simpler "test the small
golems" request.)

**Comment by Argent77** [comment]
There are already several merchants in the games, including BG1 and SoD, who can sell you ingredients and other golem-related stuff. The mod also adds a couple of new stores to SoA and ToB who specialize in golem-related stuff.
