### ISSUE TITLE
[Documentation] Any known incompatibilities? Could this be mentioned in the main README?

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-GolemConstruction#3]
Any known incompatibilities? Could this be mentioned in the main README?

Reason I ask is because I have had a few difficulties in the past with some mods
that changed things. The romance-specific mods for instance led to buggy NPC
behaviour where they would not only not talk anymore but also the side quests
no longer progressing. This is why I ask. Thanks!

**Comment by Argent77** [comment]
There is already a paragraph in the mod's [Readme](https://argent77.github.io/A7-GolemConstruction/index.html#installation) about known compatibility issues. Let me know if you find more.
