### ISSUE TITLE
[Possible small bug] Injured golems make healing in the party take longer

### ISSUE THREAD

**Issue by rubyFeedback** [Argent77/A7-GolemConstruction#9]
I think I discovered a small bug.

I just rested my party and noticed it took 44 days (!!!) to heal it.

All were in good health though - except for the golem, a flesh golem, who was close to death.

I then tested and repaired it. First repair healed him up to 50%. Now resting took 22 days, so clearly the golem was at fault.

I then repaired it again. Now the flesh golem is ok. And resting takes 8 hours.

I believe the code checks for all party members, and if injured, tries to rest until it is healed,
though it is also strange that it does not go to infinity, as these golems can not be healed
normally.

At any rate, there are a few things that could be done here:

- Modify the code to NOT check for any golems, when it comes to healing.
- If this is not possible then perhaps some flag can be set to make the golems be ignored,
or assumed they do not have to be healed by party spells.

To me this is mostly just cosmetics, so not even a real bug, but still I think it makes no real
sense to assume the game advances 44 days because of an injured golem.

**Comment by Argent77** [comment]
Yes, this is a [known issue](https://forums.beamdog.com/discussion/comment/1149741/#Comment_1149741). It's not so much a bug of this mod but rather a quirk of the game engine if you enabled the "Rest until healed" gameplay option. This is hardcoded and cannot be changed by mods. Your best bet is to uncheck the "Rest until healed" gameplay option (which I would generally advise to players).
